builds:
  - binary: dump-dumper
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: dump-dumper
    homepage: "https://github.com/Thomascogez/dump-and-dumper"
    tap:
      owner: Thomascogez
      name: dump-dumper
    commit_author:
      name: Thomascogez
      email: thomas.cogez@gmail.com

checksum:
  name_template: 'checksums.txt'