version: '3.0'

services:
  pg_without_label:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test

  pg_dump_disabled:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    labels:
      - 'dump-and-dumper.enabled=false'
      - 'dump-and-dumper.user=postgres'
      - 'dump-and-dumper.type=pg'
  pg_dump_1:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    labels:
      - 'dump-and-dumper.enabled=true'
      - 'dump-and-dumper.user=postgres'
      - 'dump-and-dumper.type=pg'

  pg_dump_2:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    labels:
      - 'dump-and-dumper.enabled=true'
      - 'dump-and-dumper.user=postgres'
      - 'dump-and-dumper.type=pg'
